version: '3.4'

services: 
  generator:
    image: levent:2.0.4
    ports: 
      - "44388:1907"
    depends_on:
      - sqlserver

  sqlserver: 
    image: microsoft/mssql-server-linux
    